### ISSUE TITLE
NPE related to java.net.NetworkInterface.getHardwareAddress() on Chromebook

### ISSUE THREAD

**Issue by fat-tire** [aaronjwood/PortAuthority#97]
FYI-- The latest 2.2.6 update from F-Droid crashes as follows on a Chromebook:

```
02-21 02:49:46.521  3402  3402 D AndroidRuntime: Shutting down VM
02-21 02:49:46.521  3402  3402 E AndroidRuntime: FATAL EXCEPTION: main
02-21 02:49:46.521  3402  3402 E AndroidRuntime: Process: com.aaronjwood.portauthority, PID: 3402
02-21 02:49:46.521  3402  3402 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.net.wifi.STATE_CHANGE flg=0x4000010 (has extras) } in com.aaronjwood.portauthority.activity.MainActivity$1@490dc87
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1132)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6320)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
02-21 02:49:46.521  3402  3402 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.net.NetworkInterface.getHardwareAddress()' on a null object reference
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at com.aaronjwood.portauthority.activity.MainActivity.d(Unknown Source)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at com.aaronjwood.portauthority.activity.MainActivity.a(Unknown Source)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at com.aaronjwood.portauthority.activity.MainActivity$1.onReceive(Unknown Source)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:1122)
02-21 02:49:46.521  3402  3402 E AndroidRuntime:        ... 7 more
```

**Comment by aaronjwood** [comment]
Thanks for reporting this.

**Comment by aaronjwood** [comment]
Will be fixed in the next release https://github.com/aaronjwood/PortAuthority/commit/05f3517a9947aff8c6992abddb3c8428443ca4f2
